services:
  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: erp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: erpdb
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - erp-network

  # Elasticsearch (Vector DB)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: erp-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=123456
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge